module(
    name = "grpc",
    repo_name = "com_github_grpc_grpc",
    version = "1.47.0",
    compatibility_level = 1,
)
bazel_dep(name = "bazel_skylib", version = "1.0.3")
bazel_dep(name = "boringssl", version = "0.0.0-20211025-d4f1ab9")
bazel_dep(name = "c-ares", version = "1.15.0", repo_name = "com_github_cares_cares")
bazel_dep(name = "abseil-cpp", version = "20210324.2", repo_name = "com_google_absl")
bazel_dep(name = "protobuf", version = "3.19.0", repo_name = "com_google_protobuf")
bazel_dep(name = "re2", version = "2021-09-01", repo_name = "com_googlesource_code_re2")
bazel_dep(name = "rules_proto", version = "4.0.0")
bazel_dep(name = "upb", version = "0.0.0-20220602-e5f2601")
bazel_dep(name = "zlib", version = "1.2.11")
bazel_dep(name = "rules_java", version = "5.1.0")
bazel_dep(name = "rules_go", version = "0.33.0", repo_name = "io_bazel_rules_go")

grpc_repo_deps_ext = use_extension("//bazel:grpc_deps.bzl", "grpc_repo_deps_ext")
use_repo(grpc_repo_deps_ext, "com_google_googleapis")
use_repo(grpc_repo_deps_ext, "com_github_cncf_udpa")
use_repo(grpc_repo_deps_ext, "envoy_api")
use_repo(grpc_repo_deps_ext, "com_envoyproxy_protoc_gen_validate")

grpc_extra_deps_ext = use_extension("//bazel:grpc_extra_deps.bzl", "grpc_extra_deps_ext")
use_repo(grpc_extra_deps_ext, "com_google_googleapis_imports")
